import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { MusicPlayerProvider } from './context/MusicPlayerContext.jsx';
import GlobalMusicPlayer from './components/GlobalMusicPlayer.jsx';
import AppNavbar from './components/Navbar.jsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hommie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MusicPlayerProvider>
          <AppNavbar />
          {children}
          <GlobalMusicPlayer />
        </MusicPlayerProvider>
      </body>
    </html>
  );
}
