
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';

import './globals.css';
import Navbar from './components/Navbar';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Hommie',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-100" suppressHydrationWarning={true}>
      <body className={`d-flex flex-column h-100 ${inter.variable}`} suppressHydrationWarning={true}>
        <Navbar />
        <main className='d-flex flex-column'>{children}</main>
      </body>
    </html>
  );
}
